# Generated by Django 3.0.8 on 2020-08-22 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='адресс доставки')),
                ('home_number', models.CharField(max_length=250, verbose_name='номер дома')),
                ('flat_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='номер квартиры')),
                ('door_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='подъезд')),
            ],
            options={
                'verbose_name': 'Курьерская доставка',
                'verbose_name_plural': 'Курьерская доставка',
            },
        ),
        migrations.CreateModel(
            name='DepartmentDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='адресса самовывоза')),
                ('is_active', models.BooleanField(default=True, verbose_name='отображать?')),
            ],
            options={
                'verbose_name': 'Самовывоз',
                'verbose_name_plural': 'Самовывоз',
            },
        ),
        migrations.CreateModel(
            name='NovayaPochta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='отделение Новой Почты')),
            ],
            options={
                'verbose_name': 'Отделение Новой Почты',
                'verbose_name_plural': 'Отделения Новой Почты',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название товара')),
                ('author', models.CharField(max_length=250, verbose_name='автор в заказе')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.FloatField(verbose_name='цена')),
                ('product_id', models.BigIntegerField(verbose_name='id продукта')),
            ],
            options={
                'verbose_name': 'Копия заказа',
                'verbose_name_plural': 'Копия заказов',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='cтатус заказа')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='дата cоздания статуса ')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='дата изменения статуса ')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='UkrPochta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='отделение Укр Почты')),
            ],
            options={
                'verbose_name': 'Отделение Укр Почты',
                'verbose_name_plural': 'Отделения Укр Почты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='имя заказчика')),
                ('last_name', models.CharField(max_length=250, null=True, verbose_name='фамилия заказчика')),
                ('telephone', models.CharField(max_length=250, null=True, verbose_name='телефон заказчика')),
                ('email', models.CharField(max_length=250, null=True, verbose_name='эл. заказчика')),
                ('user_comment', models.TextField(blank=True, null=True, verbose_name='комментарий заказчика')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='комментарий администратора')),
                ('city_delivery', models.CharField(max_length=250, null=True, verbose_name='город')),
                ('current_status', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Status', verbose_name='статус заказа')),
                ('deliveryman_way', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.DeliveryMan', verbose_name='курьерская доставка')),
                ('departmen_way', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.DepartmentDelivery', verbose_name='самовывоз')),
                ('nova_post_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.NovayaPochta', verbose_name='доставка новой почтой')),
                ('order_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderProduct', verbose_name='копия заказ')),
                ('responsible_delivery_man', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryorders', to=settings.AUTH_USER_MODEL, verbose_name='ответственный за доставку')),
                ('responsible_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managerorders', to=settings.AUTH_USER_MODEL, verbose_name='ответственный менеджер')),
                ('ukr_post_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.UkrPochta', verbose_name='доставка новой почтой')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userorders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
