# Generated by Django 2.2.1 on 2020-04-20 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название товара')),
                ('author', models.CharField(max_length=250, verbose_name='автор в заказе')),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Копия заказа',
                'verbose_name_plural': 'Копия заказов',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='cтатус заказа')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='дата cоздания статуса ')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='дата изменения статуса ')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.TextField(verbose_name='комментарий юзера')),
                ('admin_comment', models.TextField(verbose_name='комментарий администратора')),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Status', verbose_name='статус заказа')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderProduct', verbose_name='копия заказ в корзину')),
                ('responsible_delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryorders', to=settings.AUTH_USER_MODEL)),
                ('responsible_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managerorders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userorders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='адресса самовывоза')),
                ('is_active', models.BooleanField(default=True, verbose_name='отображать?')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
            },
        ),
    ]
