# Generated by Django 3.0.8 on 2020-08-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='способ оплаты'),
        ),
    ]
