# Generated by Django 3.0.8 on 2020-08-22 04:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='категория')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Ganre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='жанр книги')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название товара')),
                ('age', models.CharField(blank=True, choices=[('для детей', 'для детей'), ('для школьников', 'для школьников'), ('для подростков', 'для подростков'), ('для взрослых', 'для взрослых'), ('для всех возрастов', 'для всех возрастов'), ('0+', '0+'), ('16+', '16+'), ('18+', '18+'), ('12+', '12+')], max_length=250, null=True, verbose_name='возрастное ограничение')),
                ('pub_year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1900), products.models.max_value_current_year])),
                ('language', models.CharField(blank=True, choices=[('укранский', 'укранский'), ('английский', 'английский'), ('русский', 'русский')], max_length=250, null=True, verbose_name='язык')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='количество страниц')),
                ('price', models.FloatField(default=0, verbose_name='цена')),
                ('stock', models.FloatField(default=0, verbose_name='скидки')),
                ('to_show', models.BooleanField(default=True, verbose_name='отображать?')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки ')),
                ('up_date', models.DateTimeField(auto_now=True, verbose_name='дата обновления ')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='издательство')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='имя переводчика')),
                ('last_name', models.CharField(max_length=250, verbose_name='фамилия переводчика')),
            ],
            options={
                'verbose_name': 'Переводчик',
                'verbose_name_plural': 'Переводчики',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='имя автора')),
                ('last_name', models.CharField(max_length=250, verbose_name='фамилия автора')),
            ],
            options={
                'verbose_name': 'Писатель',
                'verbose_name_plural': 'Писатели',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='products_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания ')),
                ('up_date', models.DateTimeField(auto_now=True, verbose_name='дата обновления ')),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='фото товара')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ManyToManyField(to='products.Writer', verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='ganre',
            field=models.ManyToManyField(to='products.Ganre', verbose_name='жанр'),
        ),
        migrations.AddField(
            model_name='product',
            name='pub_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.PublishingHouse', verbose_name='издательство'),
        ),
        migrations.AddField(
            model_name='product',
            name='translator',
            field=models.ManyToManyField(blank=True, to='products.Translator', verbose_name='переводчик'),
        ),
    ]
